#include "coursera.h"

//	throw exception(); кидаем исключение
//	throw runtime_error(string s или поток);
//	throw invalid_argument(); - бросать, если что-то не так с вх. данными
//	throw domain_error(); - бросать, если нарушается, напр., математические условия (деление на ноль, корень из отриц. числа)
//	throw system_error();

// опасный код заносим в try {...} 
//						 catch (exception& ex) {
//						 	ex.what(); -- если передали через runtime_error}

int main() {
	return 0;
}
